import { images } from "./constants";
export const data = [
  {
    id: 1111,
    img1: images.Tshirt2_ed,

    title: "ADIDAS MasterClass",
    price: 899,
  },
  {
    id: 1112,
    img1: images.Tshirt2_og,

    title: "ADIDAS MenTypography",
    price: 389,
  },
  {
    id: 1113,
    img1: images.Tshirt3_og,

    title: "ADIDAS Men Solid Rou,nd neck cotton blend",
    price: 189,
  },
  {
    id: 1114,
    img1: images.Tshirt2_og,

    title: "ADIDAS MenTypography",
    price: 389,
  },
  {
    id: 1231,
    img1: images.Shirt1_og,

    title: "PUMA:Washed Cut Away Collar Casual Shirt",
    price: 899,
  },
  {
    id: 1242,
    img1: images.Shirt2_og,

    title: "PUMA:Men Regular, Slim, Tailored Fit",
    price: 289,
  },
  {
    id: 1253,
    img1: images.Tshirt3_ed,

    title: "ADIDAS Men Solid Rou,nd neck cotton blend",
    price: 189,
  },
  {
    id: 1114,
    img1: images.Tshirt2_ed,

    title: "ADIDAS MenTypography",
    price: 389,
    rating: 4,
  },
  {
    id: 1115,
    img1: images.Hoodie1_og,
    title: "NIKE:Men Full Sleeve Printed Hooded Sweatshirt",
    price: 239,
    rating: 4,
  },
  {
    id: 1116,
    img1: images.Hoodie2_og,
    logo: images.nike_logo,
    title: "NIKE Men Full Sleeve Printed Hooded Sweatshirt",
    price: 899,
    rating: 3,
  },
  {
    id: 1117,
    img1: images.Hoodie3_og,
    logo: images.nike_logo,
    title: "NIKE Men Full Sleeve Printed Hooded Sweatshirt",
    price: 8559,
    rating: 5,
  },
  {
    id: 1118,
    img1: images.Hoodie4_og,
    logo: images.puma_logo,
    title: "PUMA Men Full Sleeve Printed Hooded Sweatshirt",
    price: 499,
    rating: 3,
  },
  {
    id: 1119,
    img1: images.Pants1_og,
    logo: images.levis_log,
    title: "LEVI'S 512 Men Tapered Fit Mid Rise",
    price: 3099,
    rating: 5,
  },
  {
    id: 1120,
    img1: images.Pants2_og,
    logo: images.levis_log,
    title: "LEVI'S Men Slim Mid Rise ",
    price: 2699,
    rating: 4,
  },
  {
    id: 1121,
    img1: images.Pants3_og,
    logo: images.levis_log,
    title: "LEVI'S Men Solid Green Track Pants",
    price: 1499,
    rating: 3,
  },
  {
    id: 1122,
    img1: images.Pants1_ed,
    logo: images.levis_log,
    title: "LEVI'S 512 Men Tapered Fit Mid Rise",
    price: 1499,
    rating: 4,
  },
  {
    img1: images.kids1,
    logo: images.puma_logo,
    id: 123,
    title: "Puma kid's Typography",
    price: 2000,
    rating: 5,
  },
  {
    img1: images.kids2,
    logo: images.puma_logo,
    id: 124,
    title: "Kid's summer wear",
    price: 1000,
    rating: 4,
  },
  {
    img1: images.kids3,
    logo: images.puma_logo,
    id: 125,
    title: "Children",
    price: 2000,
    rating: 5,
  },
  {
    img1: images.kids4,
    logo: images.puma_logo,
    id: 126,
    title: "The right size matters",
    price: 2700,
    rating: 5,
  },
  {
    img1: images.women1,
    logo: images.puma_logo,
    id: 127,
    title: "Women Typography",
    price: 1000,
    rating: 3,
  },
  {
    img1: images.women4,
    logo: images.puma_logo,
    id: 128,
    title: "PUMA Women Jeans",
    price: 1500,
    rating: 4,
  },
  {
    img1: images.women5,
    logo: images.puma_logo,
    id: 129,
    title: "WoMen Typography",
    price: 2000,
    rating: 5,
  },
  {
    img1: images.women6,
    logo: images.puma_logo,
    id: "123",
    title: "Women Jeans",
    price: 500,
    rating: 2,
  },
  {
    img1: images.shoe1,
    logo: images.puma_logo,
    id: 130,
    title: "PURE XT MEN'S TRAINING SHOES",
    price: 5000,
    rating: 5,
  },
  {
    img1: images.shoe2,
    logo: images.nike_logo,
    id: 131,
    title: "Fuse 2.0 Men's Training shoes",
    price: 9000,
    rating: 5,
  },
  {
    img1: images.shoe3,
    logo: images.puma_logo,
    id: 132,
    title: "Cell Vive Running shoes",
    price: 4000,
    rating: 4,
  },
  {
    img1: images.shoe4,
    logo: images.puma_logo,
    id: 133,
    title: "Cell Pro Running shoes",
    price: 4000,
    rating: 5,
  },
  {
    img1: images.shoe5,
    logo: images.adidas_logo,
    id: 134,
    title: "Gazelle Shoes",
    price: 5000,
    rating: 5,
  },
  {
    img1: images.shoe6,
    logo: images.nike_logo,
    id: 135,
    title: "Air Sports Shoe",
    price: 2000,
    rating: 3,
  },
  {
    img1: images.shoe7,
    logo: images.adidas_logo,
    id: 136,
    title: "Ultraboost Running Shoes",
    price: 6200,
    rating: 5,
  },
  {
    img1: images.shoe1,
    logo: images.puma_logo,
    id: 130,
    title: "PURE XT MEN'S TRAINING SHOES",
    price: 5000,
    rating: 5,
  },
];
